#!/bin/bash


echo "do autowizard false"
echo "syslog remote-action 1"
echo " syslog-server               10.145.20.20"
echo " port                        6514"
echo " source-address-or-interface $1"
echo " template                    ietf-syslog-protocol-23"
echo "!"
echo "syslog remote-action 2"
echo " syslog-server               10.62.14.36"
echo " port                        6514"
echo " source-address-or-interface $1"
echo " template                    ietf-syslog-protocol-23"
echo "!"
echo "syslog rule 1"
echo " action remote 1"
echo "!"
echo "syslog rule 2"
echo " action remote 2"
echo "!"


echo "do autowizard false"
echo "syslog remote-action 1"
echo " syslog-server               10.145.20.20"
echo " port                        6514"
echo " source-address-or-interface $2"
echo " template                    ietf-syslog-protocol-23"
echo "!"
echo "syslog remote-action 2"
echo " syslog-server               10.62.14.36"
echo " port                        6514"
echo " source-address-or-interface $2"
echo " template                    ietf-syslog-protocol-23"
echo "!"
echo "syslog rule 1"
echo " action remote 1"
echo "!"
echo "syslog rule 2"
echo " action remote 2"
echo "!"


echo "do autowizard false"
echo "syslog remote-action 1"
echo " syslog-server               10.145.20.20"
echo " port                        6514"
echo " source-address-or-interface $3"
echo " template                    ietf-syslog-protocol-23"
echo "!"
echo "syslog remote-action 2"
echo " syslog-server               10.62.14.36"
echo " port                        6514"
echo " source-address-or-interface $3"
echo " template                    ietf-syslog-protocol-23"
echo "!"
echo "syslog rule 1"
echo " action remote 1"
echo "!"
echo "syslog rule 2"
echo " action remote 2"
echo "!"


echo "do autowizard false"
echo "syslog remote-action 1"
echo " syslog-server               10.145.20.20"
echo " port                        6514"
echo " source-address-or-interface $4"
echo " template                    ietf-syslog-protocol-23"
echo "!"
echo "syslog remote-action 2"
echo " syslog-server               10.62.14.36"
echo " port                        6514"
echo " source-address-or-interface $4"
echo " template                    ietf-syslog-protocol-23"
echo "!"
echo "syslog rule 1"
echo " action remote 1"
echo "!"
echo "syslog rule 2"
echo " action remote 2"
echo "!"
